service: timtree-line-bot

frameworkVersion: ">=2.1.0 <3.0.0"

provider:
  name: aws
  runtime: ruby2.7

functions:
  webhook:
    handler: handler.webhook
    # 今回はLambda Endpointを使うためAPIGatewayは無効化
    url: true
    # events:
    #   - http:
    #       path: webhook
    #       method: post
    environment:
      TIME_TREE_ACCESS_TOKEN: ${env:TIME_TREE_ACCESS_TOKEN}
      LINE_CHANNEL_SECRET: ${env:LINE_CHANNEL_SECRET}
      LINE_CHANNEL_TOKEN: ${env:LINE_CHANNEL_TOKEN}

plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      - bundle install --deployment
